In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
from scipy import stats

<ipython-input-1-dd216727775a>:4: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-whitegrid')


In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df_zero=pd.read_csv("/content/drive/MyDrive/OCR/zero.csv")
df_zero.head()

1415.3481578826904  1144.0928039550781  584.4600205421448  \
0          172.427917           13.502123          25.078311   
1           55.236444            4.472136           0.000000   
2         5847.057495          797.036980           0.000000   
3         5553.329316         1051.139648          14.764823   
4           22.000000          225.029463         537.716319   

   20.411736488342285  23.162277698516846        0.0  10.29563045501709  \
0            6.324555           36.324555  31.501523          44.120690   
1            0.000000           50.072687   8.944272          43.584553   
2            0.000000            4.000000   0.000000           1.414214   
3           13.038404           46.324555  12.083046           0.000000   
4            0.000000           10.000000   0.000000           0.000000   

       0.0.1  1528.3334374427795  7616.734094619751  ...  11815.842900276184  \
0  57.837166           62.047053        7050.503892  ...          635.978488   
1  16.126454          200.055321        7564.522428  ...         8800.187283   
2   0.000000         2124.764025        6595.314878  ...        15102.466558   
3   0.000000          826.838549        9720.476286  ...        16542.187144   
4   0.000000         2144.265957        7406.618280  ...         5062.030109   

   15009.077007293701  1905.022220134735  1971.7217183113098  \
0        27409.661001        7129.251534         1462.875371   
1        10492.987950        1983.831565         1538.439027   
2        19313.723735        1346.291481          706.329228   
3        21422.317442        3531.956900         1583.268909   
4         6220.666451        2783.931748         2353.384500   

   7302.258755683899  6913.278270244598  3325.5373106002808  \
0         657.951306         883.983651           46.897530   
1        1330.668217        2493.832486         1695.038421   
2         593.488188        1126.126172          982.653557   
3         573.780554        1419.922666         1212.220311   
4        4045.284052        3239.871605         3071.026835   

   1740.9365648031235  9650.280717849731  0  
0          184.109048        3377.529464  0  
1         3447.515554       17652.492389  0  
2         1648.611084        9184.303374  0  
3         1717.993612       11639.435220  0  
4         1259.682901        7463.184676  0  

[5 rows x 65 columns]

In [5]:
df_zero.shape

(572, 65)

In [8]:
df_one=pd.read_csv("/content/drive/MyDrive/OCR/one.csv")
df_one.head()


18.649110794067383  32.77154326438904  12.806248664855957  \
0           15.071068           7.245165            7.615773   
1           53.094885          17.632313         1192.196594   
2           62.249031           0.000000            7.211102   
3           24.000000          11.661903            0.000000   
4            6.000000           0.000000           11.661903   

   652.7837715148926  948.4467868804932  403.71485567092896  \
0         333.559657         263.962502           18.602325   
1        1034.561431          65.857277           29.176095   
2           0.000000         224.000000            0.000000   
3           5.099020         968.873566         1641.490578   
4         475.748409         261.781925          190.394321   

   525.1623401641846  626.414547920227  69.41218852996826  296.52362418174744  \
0          36.004808          5.099020        1367.297273         3552.912373   
1         398.423987        899.227608        1556.159193         1005.966701   
2        3216.342170       3557.451297        2559.573927         1141.187783   
3         871.292933        867.118198         645.331085         2424.393638   
4         343.632786       1416.172628        4734.807615         2378.887064   

   ...  57.12358856201172  19374.637844085693  4.242640495300293  \
0  ...        1858.647873         4314.687668         113.972775   
1  ...         235.909674        38427.697808         703.591243   
2  ...           0.000000            0.000000           0.000000   
3  ...       10811.790234         4080.787733         984.034516   
4  ...         509.743797          585.237324           0.000000   

   28.932830810546875       0.0.2  101.03840637207031  488.55994033813477  \
0           54.709584   60.192193         4397.319644         3357.048076   
1           15.811388   61.728782         3883.723660         2630.761076   
2            0.000000    0.000000          510.880616            0.000000   
3          513.072739  108.615862         5608.535509         2717.296660   
4            4.472136    0.000000           74.000001            0.000000   

   1430.650117278099  2904.1398849487305  1  
0        2826.648831        14412.342169  1  
1        2099.258311         3121.817831  1  
2        2969.948324        18019.475761  1  
3        1832.587014        23008.028299  1  
4          49.107153        12510.895473  1  

[5 rows x 65 columns]

In [9]:
df_one.shape

(572, 65)

In [10]:
df_two=pd.read_csv("/content/drive/MyDrive/OCR/two.csv")
df_two.head()

2.0  17.506732940673828  23.367149353027344  1122.2692923545837  \
0  511.153900          551.265915         1283.683777            0.000000   
1    8.000000            0.000000            0.000000         6587.970604   
2   14.000000           43.062463         1333.157530         2223.989208   
3   32.142136           19.877316            0.000000         4395.652689   
4   64.088682          104.070714           28.873006           17.733044   

   4758.644742012024  789.961995601654  602.0339508056641  358.86386919021606  \
0          32.000000          0.000000          34.586335            0.000000   
1        1073.218361        803.540375        1495.258629         2414.183506   
2         513.211548        170.978278         558.923700          253.484571   
3        1042.396667        713.666615         404.845239          657.634125   
4          41.016541         37.186046          57.625365           38.642965   

   930.9957995414734  416.74212646484375  ...  2364.2047476768494  \
0        2728.235420         4068.899075  ...         1429.103443   
1        3381.594109         1363.722969  ...         4314.900727   
2         347.665751         1019.542017  ...          801.831574   
3         244.000000          538.631302  ...          390.275390   
4         789.123149         1502.228679  ...          133.172636   

   5871.178845405579  12574.411587953568  4360.392528533936  \
0        6449.052223        15657.718158        3924.577697   
1        3349.805978         5736.274190       11198.485258   
2        3375.292195        10199.261902         631.046655   
3        2920.520301         1275.423861        6681.050826   
4         862.921661         8818.752254        3027.856989   

   5967.155598640442  10707.283386707306  970.0873498916626  643.266956448555  \
0        8264.700876         3160.104864         587.740901        310.112819   
1        3921.226862        12851.822411        1961.614010       1543.096550   
2        5159.586079         4455.693938         526.557348        340.216223   
3        7418.315685         6040.470710         576.570700        379.253587   
4        1157.882380         9157.444978         558.718680        974.031016   

   2213.746837615967  2  
0        2234.173045  2  
1        3764.180492  2  
2         756.276301  2  
3         683.720676  2  
4         915.270987  2  

[5 rows x 65 columns]

In [11]:
df_two.shape

(572, 65)

In [12]:
df_three=pd.read_csv("/content/drive/MyDrive/OCR/three.csv")
df_three.head()

42.50077295303345  11.313708066940308  31.49439001083374  \
0           0.000000            0.000000           0.000000   
1          21.341664            4.242640          28.602325   
2          14.324555           31.240999        1850.893681   
3        1734.822432         1217.614120         407.203934   
4          29.162278           18.558874          12.806249   

   16.522594451904297  46.44068384170532  40.29970932006836  \
0         4603.259674        3883.722000        1314.992653   
1         1144.631363        3024.328190         506.025093   
2         2325.588973         562.160393         532.518046   
3          101.368002          24.000000           0.000000   
4           15.379941          38.324555          27.961800   

   50.22795045375824  1413.750099658966  2806.4988222122192  \
0        1482.508564        1831.897156         3011.046373   
1         422.057134         583.342553          353.368327   
2         339.942771         404.751083          726.756945   
3           1.414214          15.811389         1652.238962   
4          16.560045          53.438272         1864.177578   

   2287.037871360779  ...  6438.688903808594  13846.253865718842  \
0         794.870358  ...        7593.930537         8633.125538   
1         797.704912  ...        4930.754580         8219.050799   
2        1141.190993  ...        4823.505694         6268.995008   
3        3737.452920  ...        5242.299935         7300.137636   
4        5679.973177  ...        4088.253597        14341.270097   

   10781.597502708435  7165.28920841217  8871.551753997803  \
0         3829.615595       6054.805661       18406.783375   
1         3230.922014       2969.971573       12735.274442   
2         3514.412878       3495.114981        4063.512447   
3         2505.165334       3051.153817        7674.632093   
4         7331.610573       7907.433034        7276.567420   

   2045.3216671943665  1557.6613006591797  5566.124696612358  \
0         9287.959272          835.839119        6612.605938   
1         4115.733760         1314.914043        2565.965134   
2         1159.308758         1471.382057        2486.622898   
3         3233.947606         2685.177590        2016.716074   
4         2085.981267         1104.078547        4487.533488   

   8125.011614322662  3  
0        9049.162895  3  
1        4755.183955  3  
2        3728.731942  3  
3        3704.795367  3  
4        6512.731614  3  

[5 rows x 65 columns]

In [13]:
df_three.shape

(572, 65)

In [14]:
df_four=pd.read_csv("/content/drive/MyDrive/OCR/four.csv")
df_four.head()

77.92348766326904  76.56310880184174  110.69532108306885  \
0          78.686251          42.793052           76.898512   
1          48.246211          64.166610           43.614616   
2          84.362043          43.163365           17.029387   
3          66.000001          56.734946           34.483036   
4          79.676519          43.173716           19.299012   

   33.597063064575195  44.32455539703369  38.63020706176758  \
0           50.787906          83.428050          36.176341   
1           83.268568          87.733578          35.361966   
2           47.678451          36.542218          27.888544   
3           87.775077          94.223271          31.754539   
4            9.055386          50.431385          22.383540   

   42.56326234340668  20.4268217086792  67.89639663696289  68.96238422393799  \
0          34.352113         39.430806          80.530421          38.872252   
1          77.882911         18.490080         112.121421         119.951755   
2         103.484076         52.900882         122.417747         175.419602   
3          74.635753         13.341664          68.547680          34.361229   
4           4.472136         31.477493         196.747880        2297.112440   

   ...  10164.941886425018  9742.706119060516  8283.882418632507  \
0  ...         6002.288416        9996.620994        6848.079377   
1  ...        10095.516418       12165.401048       11523.227620   
2  ...        17604.669466       12754.600080        6514.159164   
3  ...         2293.543003       19868.935223       16412.204885   
4  ...         2441.564678       15883.390076        5991.818394   

   1091.3276538848877  3726.345808982849  6301.304844856262  \
0          786.651735        5960.980426        7377.484713   
1         3866.653231        5435.758996        8107.877362   
2         1954.211193        4661.058030        4463.581942   
3         7255.074138        8870.190253       12262.565071   
4         2300.383575        2479.242322        2054.094354   

   2664.7818279266357  2427.8919390439987  13351.860499858856  4  
0         2313.308799         2555.029812         8743.002600  4  
1         4287.901989         5078.442632        16961.090706  4  
2         3498.765757         3528.113284        15597.157274  4  
3         2877.026743         1784.757593         1436.738702  4  
4          362.096680          798.661425          988.777813  4  

[5 rows x 65 columns]

In [15]:
df_four.shape

(572, 65)

In [16]:
df_five=pd.read_csv("/content/drive/MyDrive/OCR/five.csv")
df_five.head()

26.165525436401367  876.6860628128052  351.3244094848633  \
0           36.507508          51.315281          34.530560   
1           84.479228          53.804267          27.802363   
2           55.486833          77.173062          17.888544   
3           42.176014         856.234512        1514.852966   
4           40.176014          18.439089           0.000000   

   40.20012092590332  26.439088821411133        0.0      0.0.1  \
0          44.110770           65.017238   0.000000  14.371631   
1          42.063882           95.271751  27.510541  35.751475   
2          12.217663           31.071068   7.615774  29.120118   
3        1340.703924           16.000000   0.000000   0.000000   
4          20.882323           64.142136  33.106842  28.178005   

   2371.792734146118  6401.062250137329  1198.0183506011963  ...  \
0          29.489611         111.310539          102.244406  ...   
1          66.462947         434.414051          913.552436  ...   
2          15.297058        3484.740741         2853.254485  ...   
3          56.571463        6302.289334         4293.092274  ...   
4         100.489144       11466.446292         1425.932642  ...   

   3368.436556816101  3816.816143512726  1748.1620407104492  \
0        4820.390534       11108.331187        10776.241080   
1        5418.419881        4766.422024         3250.299105   
2        2681.322601        3615.129541         2964.104079   
3        1483.195483         663.574049         1867.868174   
4        1832.626032        1858.751155         2313.158656   

   1540.045641899109  2844.4521107673645  9196.887199401855  4333.29563331604  \
0        9245.419520         5568.280272       12988.710657       9921.990106   
1        1897.573771         1787.807969        3279.373697       5255.675533   
2        2860.862680        11861.991252       23121.434858      15088.363664   
3        1710.942340         7514.242830         541.020768      17490.944870   
4        2350.719255         5918.587013       10211.592786       6781.231478   

   3666.09598839283  7904.659917831421  5  
0       8738.566473        6280.085257  5  
1       5101.721560        6664.147071  5  
2       6235.503524        4155.282773  5  
3       4000.638099        2823.444118  5  
4       5745.576232        7591.156143  5  

[5 rows x 65 columns]

In [17]:
df_five.shape

(572, 65)

In [18]:
df_six=pd.read_csv("/content/drive/MyDrive/OCR/six.csv")
df_six.head()

24.0  2288.3635909557343  476.72119140625  18.440683841705322  \
0  52.135944         1418.870282        20.000000           23.197522   
1  69.317279           69.649393        16.126582            9.055386   
2  86.615936          389.365297         0.000000            6.324555   
3  22.000000          121.932382         0.000000           10.198039   
4  60.142136         3956.471361        58.000000            0.000000   

   43.071067810058594  16.552946090698242  19.235383987426758  \
0           51.071069           14.767766            0.000000   
1           59.055386           14.826876           44.485830   
2           11.071068            7.615773           10.303088   
3           26.000000           14.433277           19.798989   
4           22.324555            0.000000           15.231546   

   53.76989030838013  157.16325855255127  7839.279670596123  ...  \
0          17.304414           64.029053        7890.733013  ...   
1          31.461659           89.666663        1314.822037  ...   
2          26.380069          116.346680        7076.242925  ...   
3          12.649111          127.768730        5854.123216  ...   
4           0.000000         2487.940720        7813.977539  ...   

   8001.825980186462  6485.792782783508  3509.46320104599  2381.620518684387  \
0        6967.597984        6163.565887       4269.532277        3526.545480   
1        6476.128059        8937.218821       3222.039728        2352.159792   
2        7145.002053        6088.043501       2840.366864        2571.054659   
3        4725.705947        5831.607889       3586.803360        3338.590044   
4        7458.586461        8746.194938       3241.167171        3168.934480   

   5356.118947029114  6614.824556350708  4995.441761016846  5906.851224780083  \
0       11942.536516       11761.560184        9951.850400        6437.415634   
1        4616.611830        6097.308992        5525.348749        5875.570758   
2        6803.956827        8832.611058        7114.841393        6557.812916   
3       11373.101490       13342.030219        8287.912622        8878.226733   
4        7569.650484        6116.780685        5871.556843        5711.911906   

   7977.063269615173  6  
0        6267.390715  6  
1        6870.530034  6  
2        7182.499174  6  
3        7448.774661  6  
4        8427.767187  6  

[5 rows x 65 columns]

In [19]:
df_six.shape

(572, 65)

In [20]:
df_seven=pd.read_csv("/content/drive/MyDrive/OCR/seven.csv")
df_seven.head()

10.0         0.0  33.838430881500244  2075.903263092041  \
0  2236.716995  665.008484         1887.615273           0.000000   
1     4.000000    0.000000            0.000000        3350.689362   
2    24.142136   15.620500            0.000000         945.523572   
3    74.000000    1.414214          632.013908         627.125122   
4    12.000000    4.242640            0.000000        4014.844166   

   7009.5592403411865  1335.490520477295  656.8959579467773  \
0         1252.976868        1137.930099         867.714752   
1         6909.454681        1849.814362        1099.157028   
2         7825.816994         600.905247        1431.496490   
3           14.000000           0.000000           4.242640   
4          299.248657          87.658432           0.000000   

   1382.474464416504  3119.5890197753906  2322.7814292907715  ...  \
0        8167.221863         4107.226593          885.950371  ...   
1        2684.784042         3456.847000          634.332874  ...   
2         194.997437         1898.663499          550.123103  ...   
3         157.872277         7670.713839         4882.204311  ...   
4         761.351227          991.120145         6211.475548  ...   

   67.04834604263306  193.0247368812561  24665.200353384018  212.917799949646  \
0           0.000000           8.000000            0.000000          0.000000   
1         161.342284       20566.451567         5909.470148        115.781321   
2          13.928389       20171.973533          352.546747         20.283524   
3         315.918743         915.128924        28432.092621        538.054858   
4         368.287965        1256.029591        12884.451563       2894.188144   

   131.52344703674316  271.9032368659973  118.84428119659424  \
0            0.000000          66.000000            0.000000   
1          142.530964         153.278725           77.106076   
2           34.270724         115.566590           32.825527   
3          150.074244         185.344973          147.862792   
4          133.142989         255.946907          133.176040   

   115.47667562961578  122.35590553283691  7  
0           60.922396         1779.747488  7  
1          147.247167           74.175121  7  
2          107.824099           20.412732  7  
3          127.465254           99.646836  7  
4          101.807616         2521.970006  7  

[5 rows x 65 columns]

In [21]:
df_seven.shape

(572, 65)

In [22]:
df_eight=pd.read_csv("/content/drive/MyDrive/OCR/eight.csv")
df_eight.head()

1782.9658107757568  599.565673828125  11.401754379272461  \
0           69.346829         53.523822           25.813428   
1           39.162278         14.259180           12.806249   
2            4.000000       1698.932851          284.077891   
3          915.932571       1565.071337           52.402287   
4          826.893559       1056.648949          112.581795   

   16.492422103881836       24.0        0.0  23.545398235321045  \
0           36.154391  56.313599   0.000000           45.254834   
1            8.246211  63.951837  36.525745           37.866654   
2            0.000000   7.099020   0.000000            0.000000   
3           15.297058  28.000000   0.000000            0.000000   
4            0.000000  26.770329  10.295630            7.211102   

   9.486833095550537  2631.6468029022217  3063.65807390213  ...  \
0          40.285529         1197.987289       1977.090958  ...   
1          35.499988           94.867609       4714.172125  ...   
2          12.165524         2735.428216       6053.838254  ...   
3           9.055386         4579.091919       4471.910830  ...   
4          46.253897         3527.497641       4951.938336  ...   

   4327.801218986511  7887.256338119507  5362.549531698227  3331.410370349884  \
0        5630.462027       11195.265500        9404.168285        2607.216489   
1        3514.337268        8920.438286        9647.781330        8823.601112   
2        5605.820148        6641.880692        6194.550091        6274.628605   
3        9834.090704       12198.992177        4430.211935        3618.450958   
4        7327.999072        6725.495804        5581.514836        5590.020942   

   2884.7092328071594  6318.252609729767  9517.592635631561  8261.79360818863  \
0         3911.513104        4690.056756       14334.505668      14780.715770   
1         6217.181482        6636.523515        9916.014174      15085.312503   
2         5465.495495        7807.023113        4706.909087       9060.859888   
3         2323.960780        4464.720603        2979.951385       9055.398315   
4         7446.281999        6901.643167        5807.705264       8885.316334   

   4967.0084528923035  8  
0        10127.016216  8  
1        13421.159699  8  
2         7409.505376  8  
3        12781.666412  8  
4         8404.634050  8  

[5 rows x 65 columns]

In [23]:
df_eight.shape

(572, 65)

In [24]:
df_nine=pd.read_csv("/content/drive/MyDrive/OCR/nine.csv")
df_nine.head()

3453.69926071167  841.5599360466003  547.5859375  373.8113718032837  \
0         20.246211        1912.290413  2921.464088           0.000000   
1         71.915997          26.144330     0.000000           6.324555   
2       3399.876081         476.789152   753.883344           0.000000   
3         32.000001         775.323607    49.526472          15.033296   
4        413.862244        3378.051441  2622.307327           0.000000   

   18.770329475402832  10.29563045501709  11.661903381347656  \
0           56.449071           0.000000           11.313708   
1           53.423575           7.615773           60.496307   
2           30.198039           4.472136            0.000000   
3           38.649111           4.472136           15.620500   
4           16.000000           0.000000            0.000000   

   9.05538558959961  2154.196502685547  3792.13853931427  ...  \
0         26.966793         140.952923       8240.615183  ...   
1         17.733044        1168.353844        701.062197  ...   
2          9.486834        2542.494325       3561.740491  ...   
3         42.070534          52.198039       5988.266601  ...   
4          0.000000        3572.199362       5948.188855  ...   

   6911.166330814362  11037.89406299591  7092.652400493622  \
0        5828.001966        7865.874680       18578.205101   
1        1511.558383        4841.574699        8624.609938   
2        8578.947646        9016.670730        6083.680073   
3        3605.390314        5538.601034       10808.632266   
4       10290.957657       10787.447941        9311.331730   

   2120.2020869255066  858.0636038780212  1072.6750001907349  \
0         6227.953117        4738.214519         5777.533470   
1         3227.522041         582.955917          533.764818   
2         3278.192723        1264.429775         1365.658488   
3         5360.060279        5556.845856         3653.936865   
4         7855.222625       14236.380250         6479.957084   

   825.758677482605  86.64915525913239  3597.099133491516  9  
0       3554.990211         122.461182        5293.496341  9  
1          8.602325         751.799640         752.514954  9  
2        247.291973          37.538890        3539.000532  9  
3       2193.194181        1037.584936        4121.273823  9  
4       1771.513934          47.023137       10243.199540  9  

[5 rows x 65 columns]

In [25]:
df_nine.shape

(572, 65)

In [37]:
column_names = [f'Column_{i}' for i in range(0, 65)]


In [38]:
df_zero.columns = column_names

In [40]:
df_zero.head()

Column_0     Column_1    Column_2   Column_3   Column_4   Column_5  \
0   172.427917    13.502123   25.078311   6.324555  36.324555  31.501523   
1    55.236444     4.472136    0.000000   0.000000  50.072687   8.944272   
2  5847.057495   797.036980    0.000000   0.000000   4.000000   0.000000   
3  5553.329316  1051.139648   14.764823  13.038404  46.324555  12.083046   
4    22.000000   225.029463  537.716319   0.000000  10.000000   0.000000   

    Column_6   Column_7     Column_8     Column_9  ...     Column_55  \
0  44.120690  57.837166    62.047053  7050.503892  ...    635.978488   
1  43.584553  16.126454   200.055321  7564.522428  ...   8800.187283   
2   1.414214   0.000000  2124.764025  6595.314878  ...  15102.466558   
3   0.000000   0.000000   826.838549  9720.476286  ...  16542.187144   
4   0.000000   0.000000  2144.265957  7406.618280  ...   5062.030109   

      Column_56    Column_57    Column_58    Column_59    Column_60  \
0  27409.661001  7129.251534  1462.875371   657.951306   883.983651   
1  10492.987950  1983.831565  1538.439027  1330.668217  2493.832486   
2  19313.723735  1346.291481   706.329228   593.488188  1126.126172   
3  21422.317442  3531.956900  1583.268909   573.780554  1419.922666   
4   6220.666451  2783.931748  2353.384500  4045.284052  3239.871605   

     Column_61    Column_62     Column_63  Column_64  
0    46.897530   184.109048   3377.529464          0  
1  1695.038421  3447.515554  17652.492389          0  
2   982.653557  1648.611084   9184.303374          0  
3  1212.220311  1717.993612  11639.435220          0  
4  3071.026835  1259.682901   7463.184676          0  

[5 rows x 65 columns]

In [41]:
df_one.columns = column_names
df_two.columns = column_names
df_three.columns = column_names
df_four.columns = column_names
df_five.columns = column_names
df_six.columns = column_names
df_seven.columns = column_names
df_eight.columns = column_names
df_nine.columns = column_names


In [42]:
master_df=pd.concat([df_one,df_two,df_three,df_four,df_five,df_six,df_seven,df_eight,df_nine]).reset_index(drop=True)

In [43]:
master_df.shape

(5148, 65)

In [44]:
master_df.head()

Column_0   Column_1     Column_2     Column_3    Column_4     Column_5  \
0  15.071068   7.245165     7.615773   333.559657  263.962502    18.602325   
1  53.094885  17.632313  1192.196594  1034.561431   65.857277    29.176095   
2  62.249031   0.000000     7.211102     0.000000  224.000000     0.000000   
3  24.000000  11.661903     0.000000     5.099020  968.873566  1641.490578   
4   6.000000   0.000000    11.661903   475.748409  261.781925   190.394321   

      Column_6     Column_7     Column_8     Column_9  ...     Column_55  \
0    36.004808     5.099020  1367.297273  3552.912373  ...   1858.647873   
1   398.423987   899.227608  1556.159193  1005.966701  ...    235.909674   
2  3216.342170  3557.451297  2559.573927  1141.187783  ...      0.000000   
3   871.292933   867.118198   645.331085  2424.393638  ...  10811.790234   
4   343.632786  1416.172628  4734.807615  2378.887064  ...    509.743797   

      Column_56   Column_57   Column_58   Column_59    Column_60    Column_61  \
0   4314.687668  113.972775   54.709584   60.192193  4397.319644  3357.048076   
1  38427.697808  703.591243   15.811388   61.728782  3883.723660  2630.761076   
2      0.000000    0.000000    0.000000    0.000000   510.880616     0.000000   
3   4080.787733  984.034516  513.072739  108.615862  5608.535509  2717.296660   
4    585.237324    0.000000    4.472136    0.000000    74.000001     0.000000   

     Column_62     Column_63  Column_64  
0  2826.648831  14412.342169          1  
1  2099.258311   3121.817831          1  
2  2969.948324  18019.475761          1  
3  1832.587014  23008.028299          1  
4    49.107153  12510.895473          1  

[5 rows x 65 columns]

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [47]:
y = master_df["Column_64"]

In [48]:
y.shape

(5148,)

In [55]:
master_df.shape

(5148, 64)

In [54]:
master_df=master_df.drop("Column_64", axis=1)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(master_df, y, test_size=0.3)

In [57]:
X_train.shape

(3603, 64)

In [58]:
X_test.shape

(1545, 64)

In [59]:
y_train.shape

(3603,)

In [60]:
y_test.shape

(1545,)

In [61]:
model = SVC(kernel='linear')

In [62]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [63]:
predictions = model.predict(X_test)
print(predictions)

[3 7 6 ... 5 1 8]


In [64]:
percentage = model.score(X_test, y_test)

In [65]:
from sklearn.metrics import confusion_matrix
res = confusion_matrix(y_test, predictions)
print("Confusion Matrix")
print(res)
print(f"Test Set: {len(X_test)}")
print(f"Accuracy = {percentage*100} %")

Confusion Matrix
[[181   0   0   1   0   0   0   0   0]
 [  0 161   1   0   0   0   0   0   0]
 [  0   0 162   0   1   0   0   0   1]
 [  0   0   0 169   0   0   1   0   1]
 [  0   0   1   0 169   1   0   0   0]
 [  0   0   0   1   0 164   0   1   0]
 [  1   0   0   0   0   0 178   0   1]
 [  1   0   1   0   1   0   0 178   0]
 [  1   0   1   0   0   0   0   1 165]]
Test Set: 1545
Accuracy = 98.83495145631068 %


In [67]:
from joblib import dump
model_filename = '/content/drive/MyDrive/OCR/svm_model.joblib'
dump(model, model_filename)

['/content/drive/MyDrive/OCR/svm_model.joblib']